import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Heading } from "@chakra-ui/react";
import {
  Wrap,
  WrapItem,
  Text,
  Table,
  Tr,
  Td,
  Th,
  Thead,
  Tbody,
} from "@chakra-ui/react";
import { IssueEdge, useRepositoryQuery } from "../types";
import Link from 'next/link'

const Home: NextPage = () => {
  const { loading, error, data, refetch } = useRepositoryQuery();
  console.log({data, error});
  return (
    <Wrap >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Table w="100%" p={4} data-testid="table-issues">
        <Thead>
          <Tr bg="tomato">
            <Th>#</Th>
            <Th>Title</Th>
            <Th>Author</Th>
          </Tr>
        </Thead>
        <Tbody>
          {data?.repository?.issues.edges.map((edge: IssueEdge, index) => {
            return (
              <Tr key={index}>
              <Td><Link href={edge.node.url}><a>{edge.node.number}</a></Link></Td>
                <Td>{edge.node.title}</Td>
                <Td>{edge.node.author?.login}</Td>
              </Tr>
            );
          })}
        </Tbody>
      </Table>
    </Wrap>
  );
};

export default Home;
